Mapping: JP-REZEPT-DPC-Mapping-for-ExtensionClaimComprehensiveEvaluation
Id: JP-REZEPT-DPC-Mapping
Title: "DPC"
Description: "レセプト電算処理システムの請求に係る記録条件仕様(DPC用)をFHIRにマッピングします。"
Source: ExtensionClaimComprehensiveEvaluation
Target: "https://shinryohoshu.mhlw.go.jp/shinryohoshu/receMenu/doReceInfo"
* extension[stayOvernightEffectiveMonth].value[x] -> "外泊レコード'(GA).請求調整区分"
* extension[stayOvernightAdjuntmentCategory].value[x] -> "外泊レコード(GA).請求調整区分"
* extension[stayOvernightAdjuntmentCategory].value[x] -> "外泊レコード(GA).外泊等"
* extension[stayOvernightAdjuntmentCategory].value[x] -> "外泊レコード(GA).診断群分類番号"
* extension[stayOvernightAdjuntmentCategory].value[x] -> "外泊レコード(GA).医療機関別係数"
* extension[stayOvernightAdjuntmentCategory].value[x] -> "外泊レコード(GA)\t翌月再入院.(転棟)予定の有無"
* extension[comprehensiveEvaluationEffectiveMonth].value[x] -> "包括評価レコード(HH).診療年月"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).請求調整区分"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).自他保険区分"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).負担区分"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).入院期間区分"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).入院期間区分別点数"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).入院期間区分別入院日数"
* extension[comprehensiveEvaluationAdjuntmentCategory].value[x] -> "包括評価レコード(HH).包括小計点数"
* extension[totalAdjustmentEffectiveMonth].value[x] -> "合計調整レコード(GT).診療年月"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).請求調整区分"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).自他保険区分"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).負担区分"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).包括小計点数合算"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).包括評価点数"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).調整点数"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).今月包括合計点数"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).診療識別"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).保険変更"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).変更年月日"
* extension[totalAdjustmentAdjuntmentCategory].value[x] -> "合計調整レコード(GT).文字データ"